name: Catholic Notice Email Bot

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 (한국시간 기준으로는 0시 UTC → 9시 KST)
  workflow_dispatch:

jobs:
  run-notice-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run notice bot
        env:
          EMAIL_APP_PASSWORD: ${{ secrets.EMAIL_APP_PASSWORD }}
        run: |
          python main.py
